version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - elastic-net

  emailservice:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_MAIL_HOST=smtp.example.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=your-email@example.com
      - SPRING_MAIL_PASSWORD=your-email-password
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - ELASTICSEARCH_ADDRESS=elasticsearch:9200
    depends_on:
      - elasticsearch
      - rabbitmq
    networks:
      - elastic-net

networks:
  elastic-net:
