version: '3.8'
services:
  email-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
      - kibana
      - rabbitmq
    environment:
      - SPRING_MAIL_HOST=smtp.example.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=user@example.com
      - SPRING_MAIL_PASSWORD=yourpassword
      - SPRING_ELASTICSEARCH_URIS=https://elasticsearch:9200
      - SPRING_ELASTICSEARCH_USERNAME=your_username
      - SPRING_ELASTICSEARCH_PASSWORD=your_password
    networks:
      - profitsoft-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - profitsoft-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0
    ports:
      - "5601:5601"
    networks:
      - profitsoft-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - profitsoft-network

networks:
  profitsoft-network:
    driver: bridge
